### ISSUE TITLE
Test the kubernetes service failing when using ICMP

### ISSUE THREAD

**Issue by pegerto** [apprenda/kuberang#32]
Hello

Since we have #27 kuberang do not pass in our service.
```
-------- OUTPUT --------
PING kubernetes (172.30.0.1): 56 data bytes

--- kubernetes ping statistics ---
5 packets transmitted, 0 packets received, 100%!p(MISSING)acket loss
------------------------

```
By default the service is not responding to ICMP. independently if the availability of the service port, why the check is ICMP and not TCP ?

**Comment by alexbrand** [comment]
Thanks @pegerto 

Is it possible you have ICMP blocked on your nodes? In any case, I tend to agree that a TCP check might be better suited here. I think we went with ping because we were seeing issues talking to the master nodes.

@dkoshkin what do you think?

**Comment by dkoshkin** [comment]
I agree, I think it should be TCP. Although for the `kubernetes` service we will probably have to ignore TLS errors.

**Comment by alexbrand** [comment]
The check introduced in #27 is actually invalid. We will remove it. We did not catch this in our regression suite because our default CIDR for services is `172.17.0.0/16`, and the fact that Docker creates the `docker0` interface with `172.17.0.1`.
