### ISSUE TITLE
Add namespace support

### ISSUE THREAD

**Issue by marcinc** [apprenda/kuberang#6]
Kuberang should be able to operate in specified (optional) kubernetes namespace, other than `default`. Currently it spins up the containers in `default` namespace which might not always be the preferred option. 

I'd like to propose that optional flag parameter e.g. `--namespace [NAMESPACE]` is added, so that smoke testing can take place in isolation. When `--namespace` is specified then namespace existence/status pre-check should also take place.

**Comment by dasmb** [comment]
Sounds perfect. Your PR looks good. But our CI pipeline is not friendly to branches right now; I will fix this and merge by end of day Monday.

**Comment by alexbrand** [comment]
Closed by #7
